project_name: fx
release:
  github:
    owner: citizenfx
    name: fx
builds:
- goos:
  - linux
  - windows
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: fx
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
